---
title: "griceinferencemturk"
output: html_document
---

```{r load_libraries}
library(tidyverse)
library(here)
library(ggthemes)
library(tidyboot)
library(lme4)
library(lmerTest)
library(jsonlite)
library(anonymizer)
library(broom.mixed)
library(knitr)
theme_set(theme_classic(base_size = 18))
```

```{r load_helper, eval = F}
read_grice_file <- function(file, newnames) {
  
    json_out <- fromJSON(file)
    id <- json_out$WorkerId
    
    raw_data <- json_out$answers$data 
    
    cols <- raw_data[1] %>%
      str_split(",") %>%
      unlist() %>%
      str_trim()
      
    raw_data[] %>%
      enframe(name = NULL) %>%
      slice(-1) %>%
      separate(value, into = cols, sep = ",") %>%
      mutate(subid = id)
}
```

```{r size_data, eval = F}
files <- list.files(here(
  "raw_data/contrast-feature-inference-size-cosub-jun_16_19/"),
                    pattern = ".json", full.names = T, recursive = T)


data <- map_df(files, read_grice_file)  %>% 
  mutate(subid = salt(subid, .seed = 400)) %>%
  mutate(subid = as.numeric(as.factor(subid)))

write_csv(data, here("data/turk_data_category_inference_size.csv"))

files <- list.files(here(
  "raw_data/contrast-feature-inference-color-cosub-jun_16_19/"),
                    pattern = ".json", full.names = T, recursive = T)


data <- map_df(files, read_grice_file)  %>% 
  mutate(subid = salt(subid, .seed = 400)) %>%
  mutate(subid = as.numeric(as.factor(subid)))

write_csv(data, here("data/turk_data_category_inference_color.csv"))
```

```{r read_inference_data}
colordata <- read_csv(here("data/turk_data_category_inference_color.csv")) %>%
  mutate(colorasked = colorasked == "TRUE",
         type = "color",
         attncheckscore = as.numeric(attncheckscore),
         searchtype = if_else(searchtype == "monochrome", "same",
                              if_else(searchtype == "polychrome",
                                      "different", searchtype))) %>%
  rename(adjective = colorasked) 

sizedata <- read_csv(here("data/turk_data_category_inference_size.csv")) %>%
  mutate(sizeasked = sizeasked == "TRUE",
         type = "size",
         attncheckscore = as.numeric(attncheckscore),
         searchtype = if_else(searchtype == "samesize", "same",
                              if_else(searchtype == "differentsizes",
                                      "different", searchtype))) %>%
  rename(adjective = sizeasked)

all_data <- bind_rows(colordata, sizedata)
```

```{r filtering}
attention_data <- all_data %>%
  filter(searchtype == "attncheck") %>%
  select(subid, attncheckscore)

attention_data %>%
  ggplot(aes(x = attncheckscore)) +
  geom_histogram(fill = "white", color = "black") 

kept_subjs <- attention_data %>%
  filter(attncheckscore >= 7) %>%
  pull(subid)

filtered_data <- all_data %>%
  filter(subid %in% kept_subjs) %>%
  filter(searchtype != "attncheck") %>%
  mutate(adjective = factor(if_else(adjective, "adjective noun", "noun"), 
         levels = c("noun", "adjective noun")),
         searchtype = factor(searchtype, levels = c("contrast", "different", "same")))
```

```{r mean_color}
means <- filtered_data %>%
  group_by(type, adjective, searchtype, subid) %>%
  summarise(percentage = mean(percentage)) %>%
  tidyboot_mean(percentage)

ggplot(means, aes(x = searchtype, color = type)) + 
  facet_wrap(~adjective) + 
  geom_pointrange(aes(y = empirical_stat, ymin = ci_lower, ymax = ci_upper), 
                      position = position_dodge(.5)) +
  scale_color_ptol()
```


```{r first_trial}
first_means <- filtered_data %>%
  group_by(type, subid) %>%
  slice(1) %>%
  group_by(type, adjective, searchtype, subid) %>%
  summarise(percentage = mean(percentage)) %>%
  tidyboot_mean(percentage)

ggplot(first_means, aes(x = searchtype, color = type)) + 
  facet_wrap(~adjective) + 
  geom_pointrange(aes(y = empirical_stat, ymin = ci_lower, ymax = ci_upper), 
                      position = position_dodge(.5)) + 
  scale_color_ptol()
```

```{r models}
model <- lmer(percentage ~ type * adjective * searchtype +
                (adjective | subid),
              control = lmerControl(optimizer = "bobyqa"),
              data = filtered_data)

tidy(model) %>%
  filter(effect == "fixed") %>%
  select(-effect, -group, -df) %>%
  kable()
```
